'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Batch = { id: string; batchCode: string; materialType: string; weightKg: string; sourceLocation: string; processedAt: string | null; currentStatus: string };
type Detail = Batch & { events: { eventType: string; eventDate: string; location: string; actor: string; notes: string | null }[] };

const api = 'http://localhost:4000';
const statuses = ['Collected', 'Processing', 'Ready', 'Delivered'];

export default function AdminBatchesPage() {
  const router = useRouter(); const [token, setToken] = useState(''); const [batches, setBatches] = useState<Batch[]>([]); const [selected, setSelected] = useState<Detail | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const saved = localStorage.getItem('traceability_admin_token'); if (!saved) { router.replace('/admin/login'); return; } setToken(saved); load(); }, [router]);
  async function load() { setLoading(true); try { const response = await fetch(`${api}/api/batches`); if (!response.ok) throw new Error('Could not load batches'); setBatches((await response.json()).batches); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load batches'); } finally { setLoading(false); } }
  async function inspect(batchCode: string) { const response = await fetch(`${api}/api/batches/${batchCode}`); if (response.ok) setSelected(await response.json()); }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const response = await fetch(`${api}/api/batches/${selected.batchCode}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ currentStatus: form.get('currentStatus') }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? 'Update failed'); return; } setMessage('Batch updated successfully.'); await load(); setSelected(data); }
  function logout() { localStorage.removeItem('traceability_admin_token'); router.push('/admin/login'); }
  return <main className="admin-page"><header className="admin-header"><div><p className="admin-eyebrow">Operations workspace</p><h1>Batch management</h1><p className="admin-muted">Review custody history and keep current statuses accurate.</p></div><button className="admin-button admin-button-secondary" onClick={logout}>Sign out</button></header>
    {message && <p className="admin-notice" role="status">{message}</p>}
    <section className="admin-grid"><div className="admin-panel"><div className="admin-panel-heading"><h2>Tracked batches</h2><button className="admin-link-button" onClick={() => load()}>Refresh</button></div>{loading ? <p className="admin-muted">Loading batches…</p> : batches.length === 0 ? <p className="admin-muted">No batches have been added yet.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Batch</th><th>Material</th><th>Weight</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{batches.map((batch) => <tr key={batch.id}><td><button className="admin-table-link" onClick={() => inspect(batch.batchCode)}>{batch.batchCode}</button><small>{batch.sourceLocation}</small></td><td>{batch.materialType}</td><td>{batch.weightKg} kg</td><td><span className={`admin-status status-${batch.currentStatus.toLowerCase()}`}>{batch.currentStatus}</span></td><td><button className="admin-link-button" onClick={() => inspect(batch.batchCode)}>View</button></td></tr>)}</tbody></table></div>}</div>
      <aside className="admin-panel admin-detail">{selected ? <><div className="admin-panel-heading"><div><p className="admin-eyebrow">Batch detail</p><h2>{selected.batchCode}</h2></div><button className="admin-link-button" onClick={() => setSelected(null)}>Close</button></div><dl className="admin-facts"><div><dt>Material</dt><dd>{selected.materialType}</dd></div><div><dt>Weight</dt><dd>{selected.weightKg} kg</dd></div><div><dt>Source</dt><dd>{selected.sourceLocation}</dd></div></dl><form onSubmit={update} className="admin-form"><label htmlFor="status">Current status</label><select id="status" name="currentStatus" defaultValue={selected.currentStatus}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button className="admin-button">Save status</button></form><h3>Event history</h3><ol className="admin-events">{selected.events.map((item) => <li key={`${item.eventDate}-${item.eventType}`}><strong>{item.eventType}</strong><span>{item.eventDate} · {item.location}</span><small>{item.actor}{item.notes ? ` — ${item.notes}` : ''}</small></li>)}</ol></> : <div className="admin-empty"><p className="admin-eyebrow">Event history</p><h2>Select a batch</h2><p className="admin-muted">Choose a row to inspect its custody and processing milestones.</p></div>}</aside></section>
  </main>;
}
